apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: laraberg-components
  annotations:
    github.com/project-slug: martynasOg/laraberg-components
    backstage.io/techdocs-ref: dir:docs
spec:
  type: other
  lifecycle: unknown
  owner: test
